name: Push files into modio-docs-internal
on:
  pull_request:
    branches:
      - "main"
    types:
      - closed
  workflow_dispatch:

    

jobs:
  push-files-to-modio-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4 
 
      - name: Push public docs to modio-docs-internal
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOCS_ACCESS_TOKEN }}
        with:
          source-directory: 'public'
          destination-github-username: "modio"
          destination-repository-name: "modio-docs-internal"
          commit-message: "docs: updating public docs from modio-docs repo"
          target-branch: main
          target-directory: public

      - name: Push public side menu to modio-docs-internal
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOCS_ACCESS_TOKEN }}
        with:
          source-directory: 'menu'
          destination-github-username: "modio"
          destination-repository-name: "modio-docs-internal"
          commit-message: "docs: updating docs menu from modio-docs repo"
          target-branch: main
          target-directory: menu
